import citu.*

class BootStrap {

    def init = { servletContext ->
		if (!EnergyFileRef.count()) {
			
			def xml1 = new EnergyFileRef(urlPath:'http://office.citu.co.uk:9020/xmlwater3.xml', category:'Water').save()
			def xml2 = new EnergyFileRef(urlPath:'http://office.citu.co.uk:9021/xmlwater4.xml', category:'Water').save()
			def xml3 = new EnergyFileRef(urlPath:'http://office.citu.co.uk:9022/xmlwater5.xml', category:'Water').save()
			def xml4 = new EnergyFileRef(urlPath:'http://office.citu.co.uk:9023/xmlwater6.xml', category:'Water').save()
			def xml5 = new EnergyFileRef(urlPath:'http://office.citu.co.uk:9024/xmlwater7.xml', category:'Water').save()
			def xml6 = new EnergyFileRef(urlPath:'http://office.citu.co.uk:9025/xmlwater8.xml', category:'Water').save()
			def xml7 = new EnergyFileRef(urlPath:'http://office.citu.co.uk:9026/xmlwater9.xml', category:'Water').save()
			def xml8 = new EnergyFileRef(urlPath:'http://office.citu.co.uk:9027/xmlwater10.xml', category:'Water').save()
			def xml9 = new EnergyFileRef(urlPath:'http://office.citu.co.uk:9028/xmlwater11.xml', category:'Water').save()
			def xml10 = new EnergyFileRef(urlPath:'http://office.citu.co.uk:9029/xmlwater12.xml', category:'Water').save()
			def xml11 = new EnergyFileRef(urlPath:'http://office.citu.co.uk:9030/xmlwater13.xml', category:'Water').save()
			def xml12 = new EnergyFileRef(urlPath:'http://office.citu.co.uk:9020/xmlelectricity3.xml', category:'Electricity').save()
			def xml13 = new EnergyFileRef(urlPath:'http://office.citu.co.uk:9023/xmlelectricity6.xml', category:'Electricity').save()
			def xml14 = new EnergyFileRef(urlPath:'http://office.citu.co.uk:9025/xmlelectricity8.xml', category:'Electricity').save()
			def xml15 = new EnergyFileRef(urlPath:'http://office.citu.co.uk:9028/xmlelectricity11.xml', category:'Electricity').save()
		}
		if (!TarrifList.count()) {
			TarrifList tl = new TarrifList(coldWaterTarrif:0.003339, hotWaterTarrif:0.006249, greyWaterTarrif:0.001365, elecTarrif:0.108, heatTarrif:0.1163).save()
		}
		if(!User.count()) {
			User phil = new User(userType: 'admin', password:'password', userName:'psellick', firstName:'Phil', lastName:'Sellick', contactEmail:'sonic@sellick.org', vmUserId:'45465654').save()
			//User ben = new User(userType: 'admin', password:'password'.encodeAsHash(), userName:'bhanson', firstName:'Ben', lastName:'Hanson', contactEmail:'ben@chilling.co.uk', vmUserId:'12154852').save()
			User ben = new User(userType: 'admin', password:'password', userName:'bhanson', firstName:'Ben', lastName:'Hanson', contactEmail:'ben@chilling.co.uk', vmUserId:'12154852').save()
			User neil = new User(userType: 'user', userName:'nillingworth', firstName:'Neil', lastName:'Illingworth', contactEmail:'neil@virginmedia.com', vmUserId:'12154852').save()
			User helen = new User(userType: 'user', userName:'hsellick', firstName:'Helen', lastName:'Sellick', contactEmail:'helen@virginmedia.com', vmUserId:'12154852').save()
			User john = new User(userType: 'user', userName:'jhiggins', firstName:'John', lastName:'Higgins', contactEmail:'john@virginmedia.com', vmUserId:'12154852').save()
			User kath = new User(userType: 'user', userName:'ksmith', firstName:'Katherine', lastName:'Smith', contactEmail:'info@catherinesmithonline.com', vmUserId:'12154852').save()
			User steve = new User(userType: 'user', userName:'ksmith', firstName:'Katherine', lastName:'Smith', contactEmail:'Stephen.Perry2@virginmedia.co.uk', vmUserId:'12154854').save()
			User ryan = new User(userType: 'user', userName:'ksmith', firstName:'Katherine', lastName:'Smith', contactEmail:'Ryan.Gilmore@virginmedia.co.uk', vmUserId:'12154855').save()
			User energy = new User(userType: 'user', userName:'energy', firstName:'energy', lastName:'energy', contactEmail:'Ryan.Gilmore@virginmedia.co.uk', vmUserId:'12154855').save()
			
			
			
			Premise Flat1 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:40, flatNo:'1', addressLine1:'Sonic House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:kath).save()
			Premise Flat2 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:76,flatNo:'2', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW15 5AS', user:steve).save()
			Premise Flat3 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:46,flatNo:'3', addressLine1:'Sonic House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:phil).save()
			Premise Flat4 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:54,flatNo:'4',addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW15 5AS', user:ben).save()
			Premise Flat5 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:40,flatNo:'5', addressLine1:'Sonic House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:john).save()
			Premise Flat6 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:54,flatNo:'6', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:helen).save()
			Premise Flat7 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:38,flatNo:'7', addressLine1:'Sonic House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:phil).save()
			Premise Flat8 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:76,flatNo:'8', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat9 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:40,flatNo:'9', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat12 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:40,flatNo:'12', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat14 = new Premise(bathrooms:2, premiseType:'Flat', core:'None', bedrooms:3, squareArea:76, flatNo:'14', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat15 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:43,flatNo:'15', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat16 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:33,flatNo:'16', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat17 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:33,flatNo:'17', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat18 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:33,flatNo:'18', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat19 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:33,flatNo:'19', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat20 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:33,flatNo:'20', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat21 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:33,flatNo:'21', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat22 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:33,flatNo:'22', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat23 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:43,flatNo:'23', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat24 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:76,flatNo:'24', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat25 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:40,flatNo:'25', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat26 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:56,flatNo:'26', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat101 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:59,flatNo:'101', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat102 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:42,flatNo:'102', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat103 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:79,flatNo:'103', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat104 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:47,flatNo:'104', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat105 = new Premise(bathrooms:2, premiseType:'Flat', core:'None', bedrooms:2, squareArea:59,flatNo:'105', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat106 = new Premise(bathrooms:2, premiseType:'Flat', core:'None', bedrooms:2, squareArea:59,flatNo:'106', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat107 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:57,flatNo:'107', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat108 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:40,flatNo:'108', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat109 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:79,flatNo:'109', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat110 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:42,flatNo:'110', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat113 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:42,flatNo:'113', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat114 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:79,flatNo:'114', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat115 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:44,flatNo:'115', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat116 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:60,flatNo:'116', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat117 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:42,flatNo:'117', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat118 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:60,flatNo:'118', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat119 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:37,flatNo:'119', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat120 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:79,flatNo:'120', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat121 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:42,flatNo:'121', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat122 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:59,flatNo:'122', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat201 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:59,flatNo:'201', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat202 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:42,flatNo:'202', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat203 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:79,flatNo:'203', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat204 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:47,flatNo:'204', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat205 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:57,flatNo:'205', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat206 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:42,flatNo:'206', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat207 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:77,flatNo:'207', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat208 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:40,flatNo:'208', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat209 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:40,flatNo:'209', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat210 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:42,flatNo:'210', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat212 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:42,flatNo:'212', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat213 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:42,flatNo:'213', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat214 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:42,flatNo:'214', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat215 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:44,flatNo:'215', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat216 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:42,flatNo:'216', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat217 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:42,flatNo:'217', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat218 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:60,flatNo:'218', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat219 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:37,flatNo:'219', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat220 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:79,flatNo:'220', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat221 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:42,flatNo:'221', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat222 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:42,flatNo:'222', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat223 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:42,flatNo:'223', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat301 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'301', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat302 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:42,flatNo:'302', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat303 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:79,flatNo:'303', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat304 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:48,flatNo:'304', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat305 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'305', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat306 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:42,flatNo:'306', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat307 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'307', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat308 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'308', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat309 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:58,flatNo:'309', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat310 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'310', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat312 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'312', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat313 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:42,flatNo:'313', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat314 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:58,flatNo:'314', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat315 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'315', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat316 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'316', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat317 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'317', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat318 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'318', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat319 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'319', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat320 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:58,flatNo:'320', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat321 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'321', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat322 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'322', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat323 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'323', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat324 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'324', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat325 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'325', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat326 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'326', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat401 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'401', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat402 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'402', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat403 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:58,flatNo:'403', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat404 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'404', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat405 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'405', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat406 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'406', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat407 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'407', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat408 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'408', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat409 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:58,flatNo:'409', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat410 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'410', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat411 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'411', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat412 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'412', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat413 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'413', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat414 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'414', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat415 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'415', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat416 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'416', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat417 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:58,flatNo:'417', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat418 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'418', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat419 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'419', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat420 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'420', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat421 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'421', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat422 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'422', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat423 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:58,flatNo:'423', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat424 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'424', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat425 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'425', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat426 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'426', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat427 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'427', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat428 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'428', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat429 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'429', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat430 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'430', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat501 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'501', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat502 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'502', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat503 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:58,flatNo:'503', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat504 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'504', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat505 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'505', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat506 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'506', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat507 = new Premise(bathrooms:2, premiseType:'Flat', core:'None', bedrooms:3, squareArea:58,flatNo:'507', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat508 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'508', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat509 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'509', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat510 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'510', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat511 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'511', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat512 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'512', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat513 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'513', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat514 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'514', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat515 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:58,flatNo:'515', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat516 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:58,flatNo:'516', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat517 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'517', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat518 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'518', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat519 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'519', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat520 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'520', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat521 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'521', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat522 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'522', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat523 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'523', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat601 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'601', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat602 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'602', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat603 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:58,flatNo:'603', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat604 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'604', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat605 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'605', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat606 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'606', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat607 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:58,flatNo:'607', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat608 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'608', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat609 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'609', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat610 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'610', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat611 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'611', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat612 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'612', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat613 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'613', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat614 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'614', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat615 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:58,flatNo:'615', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat616 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:3, squareArea:58,flatNo:'616', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat617 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'617', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat618 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'618', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat619 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'619', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat620 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'620', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat621 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'621', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat622 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:2, squareArea:58,flatNo:'622', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			Premise Flat623 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:1, squareArea:58,flatNo:'623', addressLine1:'Beanie House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:neil).save()
			
			Premise WindTurbine1 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:5, squareArea:58,flatNo:'Wind Turbine No1', addressLine1:'Phil House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:energy).save()
			Premise WindTurbine2 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:5, squareArea:58,flatNo:'Wind Turbine No2', addressLine1:'Phil House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:energy).save()
			Premise Solar1 = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:5, squareArea:58,flatNo:'Solar Energy Meter', addressLine1:'Phil House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:energy).save()
			Premise GreyWaterTotal = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:5, squareArea:58,flatNo:'Main Grey Water Meter', addressLine1:'Phil House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:energy).save()
			Premise GreyWaterTopUp = new Premise(bathrooms:1, premiseType:'Flat', core:'None', bedrooms:5, squareArea:58,flatNo:'Grey Water Top Up Meter', addressLine1:'Phil House', addressLine2:'CituGreen Est.', postCode:'SW5 3AP', user:energy).save()
							
			SetTopBox stb1 = new SetTopBox(macAddress:'44:58:29:17:2A:EC', TSMid:'12315464', premise:Flat114).save()
			SetTopBox stb2 = new SetTopBox(macAddress:'44:58:29:17:23:D2', TSMid:'345345', premise:Flat2).save()
			SetTopBox stb3 = new SetTopBox(macAddress:'44:58:29:17:C1:52', TSMid:'345564', premise:Flat3).save()
			SetTopBox stb4 = new SetTopBox(macAddress:'44:58:29:17:C1:53', TSMid:'5467345', premise:Flat4).save()
			SetTopBox stb5 = new SetTopBox(macAddress:'44:58:29:17:C1:54', TSMid:'876345354', premise:Flat5).save()
			SetTopBox stb6 = new SetTopBox(macAddress:'44:58:29:17:C1:55', TSMid:'834234', premise:Flat6).save()
			SetTopBox stb7 = new SetTopBox(macAddress:'44:58:29:17:C1:56', TSMid:'23546', premise:Flat7).save()
			SetTopBox stb8 = new SetTopBox(macAddress:'44:58:29:17:C1:57', TSMid:'36315464', premise:Flat8).save()
			SetTopBox stb9 = new SetTopBox(macAddress:'44:58:29:17:C1:58', TSMid:'6345345', premise:Flat9).save()
			SetTopBox stb12 = new SetTopBox(macAddress:'44:58:29:17:C1:59', TSMid:'6345345', premise:Flat12).save()
		}

		
	//	if (!ElecReading.count()) {
	//		def now = (new Date() - 50)

	//		Premise p = Premise.findByFlatNo("215")
	//		Premise p1 = Premise.findByFlatNo("606")
	//		Premise p2 = Premise.findByFlatNo("106")
	//		Premise p3 = Premise.findByFlatNo("608")
	// 	Premise p4 = Premise.findByFlatNo("610")
			
	//		def random = new Random()
			
	//		50.times {
			//	now = (now + 1)
		//		24.times{
				//	ElecReading tmpReading = new ElecReading(readingValueElec:random.nextInt(8), fileDate:now, premise:p1).save()
				//	ElecReading tmpReading1 = new ElecReading(readingValueElec:random.nextInt(8), fileDate:now, premise:p2).save()
				//	ElecReading tmpReading2 = new ElecReading(readingValueElec:random.nextInt(8), fileDate:now, premise:p).save()
				//	ElecReading tmpReading3 = new ElecReading(readingValueElec:random.nextInt(8), fileDate:now, premise:p3).save()
				//	ElecReading tmpReading4 = new ElecReading(readingValueElec:random.nextInt(8), fileDate:now, premise:p4).save()
				//	WaterReading tmpWater = new WaterReading(fileDate:now, readingValueCold:random.nextInt(30), readingValueHot:random.nextInt(30) + 2, readingValueGrey:random.nextInt(30) + 1, premise:p1).save()
				//	WaterReading tmpWater1 = new WaterReading(fileDate:now, readingValueCold:random.nextInt(30), readingValueHot:random.nextInt(30) + 2, readingValueGrey:random.nextInt(30) + 1, premise:p2).save()
				//	WaterReading tmpWater2 = new WaterReading(fileDate:now, readingValueCold:random.nextInt(30), readingValueHot:random.nextInt(30) + 2, readingValueGrey:random.nextInt(30) + 1, premise:p3).save()
				//	WaterReading tmpWater3 = new WaterReading(fileDate:now, readingValueCold:random.nextInt(30), readingValueHot:random.nextInt(30) + 2, readingValueGrey:random.nextInt(30) + 1, premise:p4).save()
				//	WaterReading tmpWater4 = new WaterReading(fileDate:now, readingValueCold:random.nextInt(30), readingValueHot:random.nextInt(30) + 2, readingValueGrey:random.nextInt(30) + 1, premise:p).save()
					//HeatReading tmpHeat = new HeatReading(heatReading:random.nextInt(60), heatCost:0, premise:p).save()
			//	}
		//	}
			
		//}
    }
    def destroy = {
    }
}
